# Number of days of inactivity before an issue becomes stale
# Let us go for 120 days
daysUntilStale: 120
# Number of days of inactivity before a stale issue is closed
# Pin it to 30 days
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - Dedicated Priority Support
  - critical/security bug
  - severe improvement
  - blocker
# Label to use when marking an issue as stale
staleLabel: ready-to-close?
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
   This issue has been automatically marked as stale
   because it has not had recent activity for 120 days.
   It will be closed if no further activity occurs within 30 days.
   Thank you for your contribution.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
