#!/bin/bash

# run a syslog daemon
# special version to support rsyslog 2.x on RHEL 5

if type -p rsyslogd >/dev/null ; then
        exec rsyslogd -n -i /var/run/rsyslogd.pid -f /etc/rsyslog.conf
else
        klogd -c 1 -x
        if type -p syslog-ng >/dev/null ; then
                exec syslog-ng -p /var/run/syslog-ng.pid -f /etc/syslog-ng.conf -F
        else
                exec syslogd -f /etc/syslog.conf -n 
        fi
fi
