downstream_package_name: rear
jobs:
- job: copr_build
  targets:
  - fedora-all
  - centos-stream-8-x86_64
  - centos-stream-9-x86_64
  - opensuse-leap-15.3-x86_64
  - opensuse-tumbleweed-x86_64
  trigger: pull_request
- job: upstream_koji_build
  scratch: True
  targets:
  - fedora-latest-stable
  - epel-all
  trigger: pull_request
- job: tests
  trigger: pull_request
  metadata:
  targets:
  - fedora-all
  - centos-stream-8-x86_64
  - centos-stream-9-x86_64
specfile_path: packaging/rpm/rear.spec
files_to_sync:
- .packit.yaml
- dest: rear.spec
  src: packaging/rpm/rear.spec
upstream_package_name: rear
actions:
  get-current-version:
  - grep -oP '^Version:\s+\K\S+' packaging/rpm/rear.spec
