# Generated by Cursor with Claude Opus 4.6
#
# ISO output may be written to a writable medium (e.g. USB stick) which
# should be protected against overwriting by "rear recover"
# cf. https://github.com/rear/rear/issues/1271
# This code registers the ISO filesystem label as write-protected.
# CD/DVD media (sr0, sr1, ...) are inherently protected by the removable device
# check in layout/prepare/default/250_compare_disks.sh and 300_map_disks.sh
# but ISOs booted from writable media (e.g. USB sticks or hard disks) need
# explicit write protection, analogous to what OUTPUT=USB does.

# The ISO_VOLID label (default 'REAR-ISO', see default.conf) is added
# to WRITE_PROTECTED_FS_LABEL_PATTERNS.
# When the backup is split on multiple ISOs (cf. ISO_MAX_SIZE)
# the first ISO has the label $ISO_VOLID and subsequent ISOs get
# the labels ${ISO_VOLID}_01 ${ISO_VOLID}_02 ... respectively
# so the glob pattern '${ISO_VOLID}_*' is used to match all of them.
WRITE_PROTECTED_FS_LABEL_PATTERNS+=( "${ISO_VOLID}" "${ISO_VOLID}_*" )
DebugPrint "ISO filesystem label patterns '${ISO_VOLID}' and '${ISO_VOLID}_*' added to WRITE_PROTECTED_FS_LABEL_PATTERNS"
