#!/bin/bash

# run a syslog daemon

if type -p rsyslogd >/dev/null ; then
        exec rsyslogd -c3 -n -i /var/run/rsyslogd.pid -f /etc/rsyslog.conf -M /lib
else
        klogd -c 1 -x
        if type -p syslog-ng >/dev/null ; then
                exec syslog-ng -p /var/run/syslog-ng.pid -f /etc/syslog-ng.conf -F
        else
                exec syslogd -f /etc/syslog.conf -n 
        fi
fi
