#!/bin/bash

# run a syslog daemon

if type -p rsyslogd >/dev/null ; then
        exec rsyslogd -c3 -n -i /var/run/rsyslogd.pid -f /etc/rsyslog.conf -M /lib$(test -s /lib64/imklog.so && echo 64)
elif type -p syslog-ng >/dev/null ; then
    # need get_version and version_newer functions
    . /usr/share/rear/lib/layout-functions.sh

    ng_version=$(get_version syslog-ng --version)
    if version_newer "$ng_version" "3" ; then
        # /var/empty needs to be owned by root
        chown root:root /var/empty
        exec syslog-ng -p /var/run/syslog-ng.pid -f /etc/syslog-ng-v3.conf -F --no-caps
    else
        klogd -c 1 -x
        exec syslog-ng -p /var/run/syslog-ng.pid -f /etc/syslog-ng.conf -F
    fi
elif type -p syslogd >/dev/null ; then
    klogd -c 1 -x
    exec syslogd -f /etc/syslog.conf -n
fi
