#!/bin/bash
# check inittab for "ssh:23:respawn:/bin/sshd -D"
if $(grep -q ^ssh: /etc/inittab) ; then
    if ! ls /etc/ssh/*key* &>/dev/null ; then
        # generate at least one SSH host key if there is none because
        # a running sshd without any SSH host key is not accessible from remote
        # (on the remote host one gets "Connection to recovery.system.IP.address closed.")
        # cf. build/default/500_ssh_setup.sh
        ssh-keygen -q -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key
    fi
    sed -i 's/^PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    sed -i 's/^ClientAliveInterval.*/ClientAliveInterval 0/' /etc/ssh/sshd_config
    mkdir -p /run/sshd
    exec /bin/sshd -D
fi
