#!/bin/bash

# system-setup has been split into scripts under /etc/scripts/system-setup.d
# the purpose is to have different skel areas contribute different scripts into
# the system-setup stage

# set null globbing, we need this for our scripts
shopt -s nullglob

echo "* * * Configuring Rescue System * * *"
for s in /etc/scripts/system-setup.d/*.sh ; do
	echo "Running $(basename $s)..."
	source $s
done
echo "* * * Rescue System is ready * * *"
