# store the paths to the Galaxy/Commvault client in rescue.conf

cat <<EOF >>"$ROOTFS_DIR/etc/rear/rescue.conf"

# from rescue/GALAXY11/default/600_store_galaxy_paths.sh
GALAXY11_CORE_DIRECTORY="$GALAXY11_CORE_DIRECTORY"
GALAXY11_HOME_DIRECTORY="$GALAXY11_HOME_DIRECTORY"
GALAXY11_LOG_DIRECTORY="$GALAXY11_LOG_DIRECTORY"
GALAXY11_TEMP_DIRECTORY="$GALAXY11_TEMP_DIRECTORY"
GALAXY11_JOBS_RESULTS_DIRECTORY="$GALAXY11_JOBS_RESULTS_DIRECTORY"
EOF
