.\"     Title: rear
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.74.0 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "REAR" "8" "11/15/2013" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * (re)Define some macros
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" toupper - uppercase a string (locale-aware)
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de toupper
.tr aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ
\\$*
.tr aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH-xref - format a cross-reference to an SH section
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de SH-xref
.ie n \{\
.\}
.toupper \\$*
.el \{\
\\$*
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH - level-one heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SH
.\" put an extra blank line of space above the head in non-TTY output
.if t \{\
.sp 1
.\}
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[an-margin]u
.ti 0
.HTML-TAG ".NH \\n[an-level]"
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
\." make the size of the head bigger
.ps +3
.ft B
.ne (2v + 1u)
.ie n \{\
.\" if n (TTY output), use uppercase
.toupper \\$*
.\}
.el \{\
.nr an-break-flag 0
.\" if not n (not TTY), use normal case (not uppercase)
\\$1
.in \\n[an-margin]u
.ti 0
.\" if not n (not TTY), put a border/line under subheading
.sp -.6
\l'\n(.lu'
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SS - level-two heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SS
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[IN]u
.ti \\n[SN]u
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.ps \\n[PS-SS]u
\." make the size of the head bigger
.ps +2
.ft B
.ne (2v + 1u)
.if \\n[.$] \&\\$*
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BB/BE - put background/screen (filled box) around block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BB
.if t \{\
.sp -.5
.br
.in +2n
.ll -2n
.gcolor red
.di BX
.\}
..
.de EB
.if t \{\
.if "\\$2"adjust-for-leading-newline" \{\
.sp -1
.\}
.br
.di
.in
.ll
.gcolor
.nr BW \\n(.lu-\\n(.i
.nr BH \\n(dn+.5v
.ne \\n(BHu+.5v
.ie "\\$2"adjust-for-leading-newline" \{\
\M[\\$1]\h'1n'\v'+.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.el \{\
\M[\\$1]\h'1n'\v'-.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.in 0
.sp -.5v
.nf
.BX
.in
.sp .5v
.fi
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BM/EM - put colored marker in margin next to block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BM
.if t \{\
.br
.ll -2n
.gcolor red
.di BX
.\}
..
.de EM
.if t \{\
.br
.di
.ll
.gcolor
.nr BH \\n(dn
.ne \\n(BHu
\M[\\$1]\D'P -.75n 0 0 \\n(BHu -(\\n[.i]u - \\n(INu - .75n) 0 0 -\\n(BHu'\M[]
.in 0
.nf
.BX
.in
.fi
.\}
..
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "Name"
rear \- bare metal disaster recovery and system migration tool
.SH "Synopsis"
.sp
\fBrear\fR [\fB\-dDsSvV\fR] [\fB\-r\fR \fIKERNEL\fR] \fICOMMAND\fR [\-\- \fIARGS\fR\&...]
.SH "DESCRIPTION"
.sp
Relax\-and\-Recover is the leading Open Source disaster recovery solution\&. It is a modular framework with many ready\-to\-go workflows for common situations\&.
.sp
Relax\-and\-Recover produces a bootable image\&. This image can repartition the system\&. Once that is done it initiates a restore from backup\&. Restores to different hardware are possible\&. Relax\-and\-Recover can therefore be used as a migration tool as well\&.
.sp
Currently Relax\-and\-Recover supports various boot media (incl\&. ISO, PXE, OBDR tape, USB or eSATA storage), a variety of network protocols (incl\&. sftp, ftp, http, nfs, cifs) for storage and backup as well as a multitude of backup strategies (incl\&. IBM TSM, HP DataProtector, Symantec NetBackup, Bacula, rsync, rbme)\&. This results in a bootable image that os capable of booting via PXE, DVD/CD, bootable tape or virtual provisioning\&.
.sp
Relax\-and\-Recover was designed to be easy to set up, requires no maintenance and is there to assist when disaster strikes\&. Its setup\-and\-forget nature removes any excuses for not having a disaster recovery solution implemented\&.
.sp
Recovering from disaster is made very straight\-forward by a 2\-step recovery process so that it can be executed by operational teams when required\&. When used interactively (e\&.g\&. when used for migrating systems), menus help make decisions to restore to a new (hardware) environment\&.
.sp
Extending Relax\-and\-Recover is made possible by its modular framework\&. Consistent logging and optionally extended output help understand the concepts behind Relax\-and\-Recover and help debug during development\&.
.sp
Relax\-and\-Recover comes with ABSOLUTELY NO WARRANTY; for details see the GNU General Public License at: \m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\&.html\fR\m[]
.SH "OPTIONS"
.SS "GLOBAL OPTIONS"
.PP
\-d
.RS 4

\fBdebug mode\fR
(log debug messages to log file)
.RE
.PP
\-D
.RS 4

\fBdebugscript mode\fR
(log every function call)
.RE
.PP
\-r KERNEL
.RS 4
kernel version to use (by default use running kernel)
.RE
.PP
\-s
.RS 4

\fBsimulation mode\fR
(show what scripts rear would include)
.RE
.PP
\-S
.RS 4

\fBstep\-by\-step mode\fR
(acknowledge each script individually)
.RE
.PP
\-v
.RS 4

\fBverbose mode\fR
(show progress output)
.RE
.PP
\-V
.RS 4
version information
.RE
.SS "COMMANDS"
.PP
\fBchecklayout\fR
.RS 4
check if the disk layout has changed since the last run of mkbackup/mkrescue
.RE
.PP
\fBdump\fR
.RS 4
dump configuration and system information; please run this to verify your setup
.RE
.PP
\fBformat\fR
.RS 4
format and label USB or tape media to be used with rear; first argument is the USB or tape device to use, eg\&.
\fI/dev/sdX\fR
or
\fI/dev/stX\fR
.RE
.PP
\fBhelp\fR
.RS 4
print full list of commands and options
.RE
.PP
\fBmkbackup\fR
.RS 4
create rescue media and backup the system (only for internal backup methods)
.RE
.PP
\fBmkbackuponly\fR
.RS 4
backup the system (only for internal backup methods) without creating rescue media
.RE
.PP
\fBmkrescue\fR
.RS 4
create rescue media only
.RE
.PP
\fBrecover\fR
.RS 4
recover the system; can be used only when running from the rescue media
.RE
.PP
\fBvalidate\fR
.RS 4
submit validation information
.RE
.sp
Use \fIrear \-v help\fR for more advanced commands\&.
.SH "BACKGROUND INFORMATION"
.sp
The process of bare metal disaster recovery consists of two parts:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Recreate the system layout
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Restore the data to the system
.RE
.sp
Most backup software solutions are very good at restoring data but do not support recreating the system layout\&. Relax\-and\-Recover is very good at recreating the system layout but works best when used together with supported backup software\&.
.sp
In this combination Relax\-and\-Recover recreates the system layout and calls the backup software to restore the actual data\&. Thus there is no unnessecary duplicate data storage and the Relax\-and\-Recover rescue media can be very small\&.
.sp
For demonstration and special use purposes Relax\-and\-Recover also includes an internal backup method, NETFS, which can be used to create a simple tar\&.gz archive of the system\&. For all permanent setups we recommend using something more professional for backup, either a traditional backup software (open source or commercial) or rsync with hardlink based solutions, e\&.g\&. RSYNC BACKUP MADE EASY\&.
.SH "RESCUE IMAGE CONFIGURATION"
.sp
The \FCOUTPUT\F[] variable defines how from where our rescue image will be booted and the \FCOUTPUT_URL\F[] variable defines where the rescue image should be send to\&. Possible \FCOUTPUT\F[] setting are:
.PP
OUTPUT=\fBRAMDISK\fR
.RS 4

\fB(Default)\fR
Create only the Relax\-and\-Recover initramfs\&.
.RE
.PP
OUTPUT=\fBISO\fR
.RS 4
Create a bootable ISO9660 image on disk as
\fIrear\-$(hostname)\&.iso\fR
.RE
.PP
OUTPUT=\fBPXE\fR
.RS 4
Create on a remote PXE/NFS server the required files (such as configuration file, kernel and initrd image
.RE
.PP
OUTPUT=\fBOBDR\fR
.RS 4
Create a bootable OBDR tape (optionally including the backup archive)\&. Specify the OBDR tape device by using
\FCTAPE_DEVICE\F[]\&.
.RE
.PP
OUTPUT=\fBUSB\fR
.RS 4
Create a bootable USB disk (using extlinux)\&. Specify the USB storage device by using
\FCUSB_DEVICE\F[]\&.
.RE
.sp
When using \FCOUTPUT=ISO\F[], \FCRAMDISK\F[], \FCOBDR\F[] or \FCUSB\F[] you should provide the backup target location through the \FCOUTPUT_URL\F[] variable\&. Possible \FCOUTPUT_URL\F[] settings are:
.PP
OUTPUT_URL=\fBfile://\fR
.RS 4
Write the image to disk\&. The default is in
\fI/var/lib/rear/output/\fR\&.
.RE
.PP
OUTPUT_URL=\fBfish://\fR
.RS 4
Write the image using
\FClftp\F[]
and the FISH protocol\&.
.RE
.PP
OUTPUT_URL=\fBftp://\fR
.RS 4
Write the image using
\FClftp\F[]
and the FTP protocol\&.
.RE
.PP
OUTPUT_URL=\fBftps://\fR
.RS 4
Write the image using
\FClftp\F[]
and the FTPS protocol\&.
.RE
.PP
OUTPUT_URL=\fBhftp://\fR
.RS 4
Write the image using
\FClftp\F[]
and the HFTP protocol\&.
.RE
.PP
OUTPUT_URL=\fBhttp://\fR
.RS 4
Write the image using
\FClftp\F[]
and the HTTP (PUT) procotol\&.
.RE
.PP
OUTPUT_URL=\fBhttps://\fR
.RS 4
Write the image using
\FClftp\F[]
and the HTTPS (PUT) protocol\&.
.RE
.PP
OUTPUT_URL=\fBsftp://\fR
.RS 4
Write the image using
\FClftp\F[]
and the secure FTP (SFTP) protocol\&.
.RE
.PP
OUTPUT_URL=\fBrsync://\fR
.RS 4
Write the image using
\FCrsync\F[]
and the RSYNC protocol\&.
.RE
.PP
OUTPUT_URL=\fBsshfs://\fR
.RS 4
Write the image using sshfs and the SSH protocol\&.
.RE
.SH "BACKUP SOFTWARE INTEGRATION"
.sp
Currently Relax\-and\-Recover supports the following backup methods\&. Please distinguish carefully between Relax\-and\-Recover support for 3rd party backup software and Relax\-and\-Recover internal backup methods\&. The latter also creates a backup of your data while the former will only integrate Relax\-and\-Recover with the backup software to restore the data with the help of the backup software without actually creating backups\&. This means that for all non\-internal backup software you \fBmust\fR take care of creating backups yourself\&.
.sp
Especially the \FCrear mkbackup\F[] command can be confusing as it is only useful for the internal backup methods and has no function at all with the other (external) backup methods\&. The following backup methods need to be set in Relax\-and\-Recover with the \FCBACKUP=\F[] option\&.
.sp
The following \FCBACKUP\F[] methods are external of Relax\-and\-Recover meaning that you are responsible of backups being made:
.PP
BACKUP=\fBREQUESTRESTORE\fR
.RS 4

\fB(default)\fR
Not really a backup method at all, Relax\-and\-Recover simply halts the recovery and requests that somebody will restore the data to the appropriate location (e\&.g\&. via SSH)\&. This method works especially well with an rsync bases backup that is pushed back to the backup client\&.
.RE
.PP
BACKUP=\fBDP\fR
.RS 4
Use HP Data Protector to restore the data\&.
.RE
.PP
BACKUP=\fBEXTERNAL\fR
.RS 4
Internal backup method that uses an arbitrary external command to create a backup and restore the data\&.
.RE
.PP
BACKUP=\fBGALAXY\fR
.RS 4
Use CommVault Galaxy 5 to restore the data\&.
.RE
.PP
BACKUP=\fBGALAXY7\fR
.RS 4
Use CommVault Galaxy 7 to restore the data\&.
.RE
.PP
BACKUP=\fBNBU\fR
.RS 4
Use Symantec NetBackup to restore the data\&.
.RE
.PP
BACKUP=\fBTSM\fR
.RS 4
Use IBM Tivoli Storage Manager to restore the data\&. The Relax\-and\-Recover result files (e\&.g\&. ISO image) are also saved into TSM\&.
.RE
.PP
BACKUP=\fBRBME\fR
.RS 4
Use Rsync Backup Made Easy (rbme) to restore the data\&.
.RE
.PP
BACKUP=\fBNSR\fR
.RS 4
Using EMC NetWorker (Legato) to restore the data\&.
.RE
.sp
The following \FCBACKUP\F[] methods are internal of Relax\-and\-Recover:
.PP
BACKUP=\fBNETFS\fR
.RS 4
Internal backup method which can be used to create a simple backup (tar archive)\&.
.RE
.PP
BACKUP=\fBRSYNC\fR
.RS 4
Use rsync to restore data\&.
.RE
.sp
If your favourite backup software is missing from this list, please submit a patch or ask us to implement it for you\&.
.sp
When using \FCBACKUP=NETFS\F[] you should provide the backup target location through the \FCBACKUP_URL\F[] variable\&. Possible \FCBACKUP_URL\F[] settings are:
.PP
BACKUP_URL=\fBfile://\fR
.RS 4
To backup to local disk, use
\FCBACKUP_URL=file:///directory/path/\F[]
.RE
.PP
BACKUP_URL=\fBnfs://\fR
.RS 4
To backup to NFS disk, use
\FCBACKUP_URL=nfs://nfs\-server\-name/share/path\F[]
.RE
.PP
BACKUP_URL=\fBtape://\fR
.RS 4
To backup to tape device, use
\FCBACKUP_URL=tape:///dev/nst0\F[]
or alternatively, simply define
\FCTAPE_DEVICE=/dev/nst0\F[]
.RE
.PP
BACKUP_URL=\fBcifs://\fR
.RS 4
To backup to a Samba share (CIFS), use
\FCBACKUP_URL=cifs://cifs\-server\-name/share/path\F[]\&. To provide credentials for CIFS mounting use a
\fI/etc/rear/\&.cifs\fR
credentials file and define
\FCBACKUP_OPTIONS="cred=/etc/rear/\&.cifs"\F[]
and pass along:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
username=_username_
password=_secret password_
domain=_domain_
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.PP
BACKUP_URL=\fBusb://\fR
.RS 4
To backup to USB storage device, use
\FCBACKUP_URL=usb:///dev/disk/by\-path/REAR\-000\F[]
or use a real device node or a specific filesystem label\&. Alternatively, you can specify the device using
\FCUSB_DEVICE=/dev/disk/by\-path/REAR\-000\F[]\&.
.sp
If you combine this with
\FCOUTPUT=USB\F[]
you will end up with a bootable USB device\&.
.RE
.PP
BACKUP_URL=\fBsshfs://\fR
.RS 4
To backup to a remote server via sshfs (SSH protocol), use
\FCBACKUP_URL=sshfs://\m[blue]\fBuser@remote\-system\&.domain\&.org\fR\m[]\&\s-2\u[1]\d\s+2/home/user/backup\-dir/\F[]
.sp
It is advisable to add
\fBServerAliveInterval 15\fR
in the
\FC/root/\&.ssh/config\F[]
file for the remote system (remote\-system\&.domain\&.org)\&.
.RE
.PP
BACKUP_URL=\fBiso://\fR
.RS 4
To include the backup within the ISO image\&. It is important that the
\FCBACKUP_URL\F[]
and
\FCOUTPUT_URL\F[]
variables are different\&. E\&.g\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
BACKUP_URL=iso:///backup/
OUTPUT_URL=nfs://server/path/
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.SH "CONFIGURATION"
.sp
To configure Relax\-and\-Recover you have to edit the configuration files in \fI/etc/rear/\fR\&. All \fI*\&.conf\fR files there are part of the configuration, but only \fIsite\&.conf\fR and \fIlocal\&.conf\fR are intended for the user configuration\&. All other configuration files hold defaults for various distributions and should not be changed\&.
.sp
In \fI/etc/rear/templates/\fR there are also some template files which are used by Relax\-and\-Recover to create configuration files (mostly for the boot environment)\&. Modify the templates to adjust the information contained in the emails produced by Relax\-and\-Recover\&. You can use these templates to prepend your own configurations to the configuration files created by Relax\-and\-recover, for example you can edit \fIPXE_pxelinux\&.cfg\fR to add some general pxelinux configuration you use\&.
.sp
In almost all circumstances you have to configure two main settings and their parameters: The backup method and the output method\&.
.sp
The backup method defines, how your data was saved and wether Relax\-and\-Recover should backup your data as part of the mkrescue process or wether you use an external application, e\&.g\&. backup software to archive your data\&.
.sp
The output method defines how the rescue system is written to disk and how you plan to boot the failed computer from the rescue system\&.
.sp
See the default configuration file \fI/usr/share/rear/conf/default\&.conf\fR for an overview of the possible methods and their options\&.
.sp
An example to use TSM for backup and ISO for output would be to add these lines to \fI/etc/rear/local\&.conf\fR:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
BACKUP=TSM
OUTPUT=ISO
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
And if all your systems use NTP for time synchronisation, you can also add these lines to \fI/etc/rear/site\&.conf\fR
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
TIMESYNC=NTP
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
Don\'t forget to distribute the \fIsite\&.conf\fR to all your systems\&.
.sp
The resulting ISO image will be created in \fI/var/lib/rear/output/\fR\&. You can now modify the behaviour by copying the appropriate configuration variables from \fIdefault\&.conf\fR to \fIlocal\&.conf\fR and changing them to suit your environment\&.
.SH "EXIT STATUS"
.PP
0
.RS 4
Successful program execution\&.
.RE
.PP
>0
.RS 4
Usage, syntax or execution errors\&. Check the log file in
\fI/var/log/rear/\fR
for more information\&.
.RE
.SH "EXAMPLES"
.sp
To print out the current settings for \FCBACKUP\F[] and \FCOUTPUT\F[] methods and some system information\&. This command can be used to see the supported features for the given release and platform\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
# rear dump
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
To create a new rescue environment\&. Do not forget to copy the resulting rescue system away so that you can use it in the case of a system failure\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
# rear \-v mkrescue
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SH "FILES"
.PP
/usr/sbin/rear
.RS 4
The program itself\&.
.RE
.PP
/etc/rear/local\&.conf
.RS 4
System specific configuration can be set here\&.
.RE
.PP
/etc/rear/site\&.conf
.RS 4
Site specific configuration can be set here (not created by default)\&.
.RE
.PP
/var/log/rear/
.RS 4
Directory holding the log files\&.
.RE
.PP
/tmp/rear\&.####
.RS 4
Relax\-and\-Recover working directory\&. If Relax\-and\-Recover exits with an error, you must remove this directory manually\&.
.RE
.PP
/usr/share/rear
.RS 4
Relax\-and\-Recover script components\&.
.RE
.PP
/usr/share/rear/conf/default\&.conf
.RS 4
Relax\-and\-Recover\'s included defaults\&. Contains a complete set of parameters and its explanation\&. Please do not edit or modify\&. Copy values to
\fIlocal\&.conf\fR
or
\fIsite\&.conf\fR
instead\&.
.RE
.SH "BUGS"
.sp
Feedback is welcome, please report any issues or improvements to our issue\-tracker at: \m[blue]\fBhttp://github\&.com/rear/issues/\fR\m[]
.SH "SEE ALSO"
.sp
Relax\-and\-Recover comes with extensive documentation located in \fI/usr/share/doc\fR\&.
.SH "AUTHORS"
.sp
Gratien D\'haese, Schlomo Schapiro, Jeroen Hoekx and Dag Wieers\&.
.sp
Lars Pinne (original man page)\&.
.sp
Relax\-and\-Recover is a collaborative process using Github at: \m[blue]\fBhttp://github\&.com/rear/\fR\m[]
.sp
The Relax\-and\-Recover website is located at: \m[blue]\fBhttp://relax\-and\-recover\&.org/\fR\m[]
.SH "COPYRIGHT"
.sp
(c) 2006\-2013
.sp
Schlomo Schapiro
.sp
Gratien D\'haese, IT3 Consultants
.sp
Jeroen Hoekx
.sp
Dag Wieers, Dagit Linux Solutions
.sp
Relax\-and\-Recover comes with ABSOLUTELY NO WARRANTY; for details see the GNU General Public License at \m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\&.html\fR\m[]
.SH "Notes"
.IP " 1." 4
user@remote-system.domain.org
.RS 4
\%mailto:user@remote-system.domain.org
.RE
