= Introduction

Relax-and-Recover is the leading Open Source bare metal disaster recovery
solution. It is a modular framework with many ready-to-go workflows for
common situations.

Relax-and-Recover produces a bootable image which can recreate the system's
original storage layout. Once that is done it initiates a restore from backup.
Since the storage layout can be modified prior to recovery, and disimilar
hardware and virtualization is supported, Relax-and-Recover offers the
flexibility to be used for complex system migrations.

Currently Relax-and-Recover supports various boot media (incl. ISO, PXE,
OBDR tape, USB or eSATA storage), a variety of network protocols (incl.
sftp, ftp, http, nfs, cifs) as well as a multitude of backup strategies
(incl.  IBM TSM, Micro Focus Data Protector, Symantec NetBackup, 
EMC NetWorker [Legato], Dell PowerProtect Data Manager, SEP Sesam, 
Galaxy [Simpana], Bacula, Bareos, RBME, rsync, duplicity, Borg).

Relax-and-Recover was designed to be easy to set up, requires no maintenance
and is there to assist when disaster strikes. Its setup-and-forget nature
removes any excuse for not having a disaster recovery solution implemented.

Recovering from disaster is made very straight-forward by a 2-step recovery
process so that it can be executed by operational teams when required.
When used interactively (e.g. when used for migrating systems), menus help
make decisions to restore to a new (hardware) environment.

Extending and integrating Relax-and-Recover into complex environments is made
possible by its modular framework. Consistent logging and optionally extended
output help understand the concepts behind Relax-and-Recover, troubleshoot
during initial configuration and help debug during integration.

Professional services and support are available.


== Relax-and-Recover project
The support and development of the Relax-and-Recover project takes place
on Github:

Relax-and-Recover website::
    http://relax-and-recover.org/

Github project::
    http://github.com/rear/rear/

In case you have questions, ideas or feedback about this document, you
can contact the development team on the Relax-and-Recover mailinglist at:
rear-users@lists.relax-and-recover.org.

NOTE: Note that you have to be subscribed to be able to send mails to the
Relax-and-Recover mailinglist. You can subscribe to the list at:
http://lists.relax-and-recover.org/mailman/listinfo/rear-users


== Design concepts
Based on experience from previous projects, a set of design principles were
defined, and improved over time:

 - Focus on easy and automated disaster recovery
 - Modular design, focused on system administrators
 - For Linux (and possibly Unix operating systems)
 - Few external dependencies (Bash and standard Unix tools)
 - Easy to use and easy to extend
 - Easy to integrate with *real* backup software

The goal is to make Relax-and-Recover as least demanding as possible, it will
require only the applications necessary to fulfill the job Relax-and-Recover
is configured for.

Furthermore, Relax-and-Recover should be platform independent and ideally
install just as a set of scripts that utilizes everything that the Linux
operating system provides.


== Features and functionality
Relax-and-Recover has a wide range of features:

// FIXME: Insert the various features from the Release Notes +
//        include the information from the presentations +
//        and optionally the rescue creation and recovery workflow
// FIXME: Get rid of the below list when everything is in the feature set

 - Improvements to HP SmartArray and CCISS driver integration
 - Improvements to software RAID integration
 - Disk layout change detection for monitoring
 - One-Button-Disaster-Recovery (OBDR) tape support
 - DRBD filesystem support
 - Bacula or Bareos tape support
 - Multiple DR images per system on single USB storage device
 - USB ext3/ext4 support
 - GRUB[2] bootloader re-implementation
 - UEFI support
 - ebiso support (needed by SLES UEFI ISO booting)
 - Add Relax-and-Recover entry to local GRUB configuration (optional)
 - Nagios and webmin integration
 - Syslinux boot menu
 - Storing rescue/backup logfile on rescue media
 - Restoring to different hardware
 - RHEL5, RHEL6 and RHEL7 support
 - SLES 11 and SLES 12 support
 - Debian and Ubuntu support
 - Various usability improvements
 - Serial console support auto-detected
 - Lockless workflows
 - USB udev integration to trigger mkrescue on inserting USB device
 - Beep/UID led/USB suspend integration
 - Migrate UUID from disks and MAC addressed from network interfaces
 - Integrates with Disaster Recovery Linux Manager (DRLM)
 - Data deduplication with Borg as backend
 - Block device level backup/restore


