= Tips and Tricks using Relax-and-Recover

Recovering a system should not be a struggle against time with poor
tools weighing against you. Relax-and-Recover emphasizes on a relaxing
recovery, and for this it follows three distinct rules:

 1. Do what is generally expected, if possible

 2. In doubt, ask the operator or allow intervention

 3. Provide an environment that is as convenient as possible

This results in the following useful tips and tricks:

[TIP]
====
 1. Relax-and-Recover can add its own GRUB menu entry to your local system's
    GRUB, which is convenient to restore a system without the need for an
    additional boot media. This only works if your system can (still)
    boot from the local disk and the disaster didn't destroy that disk.

 2. Relax-and-Recover automatically detects and enables serial console support.
    This is extremely useful if the only way to access the console during
    disaster is a Java-based console riddled with keyboard bugs and slow screen
    refreshes.

 3. Relax-and-Recover conveniently ships with a set of useful commands in its
    shell history. This makes it possible to quickly look for a command to help
    troubleshoot, or modify an important file during recovery.

 4. If you have keyboard problems using a HP iLO 2 Remote Console, type the
    following command +loadkeys -d+ (or simply use the up arrow key to get
    this command from your shell history).

 5. If the original system was configured to log on remotely through the use
    of SSH keys, Relax-and-Recover preserved those keys on the rescue
    environment and you can access the rescue environment from the network
    as you were used to before.

 6. During recovery at any stage you can re-run Relax-and-Recover, modify
    the layout file for recreating the structure and intervene when restoring
    the backup.
====
