
# prepare stuff for ZYPPER
COPY_AS_IS=( "${COPY_AS_IS[@]}" "${COPY_AS_IS_ZYPPER[@]}" )
COPY_AS_IS_EXCLUDE=( "${COPY_AS_IS_EXCLUDE[@]}" "${COPY_AS_IS_EXCLUDE_ZYPPER[@]}" )
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" "${REQUIRED_PROGS_ZYPPER[@]}" )
PROGS=( "${PROGS[@]}" "${PROGS_ZYPPER[@]}" )

