#
# prepare stuff for FDRUPSTREAM
#

COPY_AS_IS+=( "${COPY_AS_IS_FDRUPSTREAM[@]}" "${FDRUPSTREAM_INSTALL_PATH}" )
COPY_AS_IS_EXCLUDE+=( "${COPY_AS_IS_EXCLUDE_FDRUPSTREAM[@]}" )
PROGS+=( "${PROGS_FDRUPSTREAM[@]}" )
REQUIRED_PROGS+=( "${REQUIRED_PROGS_FDRUPSTREAM[@]}" col )
